# Generated by Django 5.0.3 on 2024-10-29 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_user_following_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAlpha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedByUserBeta', to=settings.AUTH_USER_MODEL)),
                ('userBeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followsUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='likelist',
            fields=[
                ('likelistid', models.AutoField(primary_key=True, serialize=False)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlikelist', to='network.post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikelist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userid', 'postid')},
            },
        ),
    ]
