# Generated by Django 5.0.3 on 2024-10-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followers_likelist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('userBeta', 'userAlpha')},
        ),
    ]
